### ISSUE TITLE
cannot access to graph.facebook with error in syntax

### ISSUE THREAD

**Issue by oktakun69** [dandyraka/FacebookUnfriend#5]
hello.
i don't know mean from this error.i'm already try once but still like this.
can you help me ?
![image](https://user-images.githubusercontent.com/21134642/59030136-5259ec00-888a-11e9-8028-e320cfab432e.png)

**Comment by gvoze32** [comment]
Token setau saja nggk sependek itu deh

**Comment by oktakun69** [comment]
ane udah dapet di access token terus generate token dari APP ID + APP key . udah pake 2 tpi masih belum bisa gan.

**Comment by gvoze32** [comment]
Sepertinya beda deh sama token yang dimaksud

**Comment by oktakun** [comment]
dapet tokennya dimana sih gan ? kebingungan ane

**Comment by oktakun69** [comment]
![image](https://user-images.githubusercontent.com/21134642/59070417-d50f9500-88e4-11e9-9636-9a8a027c7423.png)
udah gan tapi abis year , gada respon usernya

**Comment by gvoze32** [comment]
Iya keknya lagi error

**Comment by dandyraka** [comment]
Beda token, coba pake token iphone.
Ada di web autolike biasanya
